### ISSUE TITLE
check this out

### ISSUE THREAD

**Issue by davidosomething** [haya14busa/vim-open-googletranslate#1]
https://github.com/soimort/translate-shell
you can maybe do inline translation

**Comment by haya14busa** [comment]
Thank you for the information! :+1: I didn't know that. It looks really useful.

I guess translate-shell scrapes Google Translate page instead of using Google Translate API.
I wonder is it ok for translation service...

Maybe, I can use translate-shell as a hidden feature....?

**Comment by haya14busa** [comment]
I decided not to add integration with translate-shell, because it uses internal API and it must be problem.
Google provides Google Translate API instead, so I may create a plugin using public API in the future.

But, anyway, thanks again!

**Comment by haya14busa** [comment]
I created an another plugin which uses Google Translation API.
- https://github.com/haya14busa/gtrans (CLI tool)
- https://github.com/haya14busa/vim-gtrans (depends on gtrans)

vim-gtrans supports to output translated result to echo area and Vim buffer.
